FROM nvidia/cuda:12.0.0-cudnn8-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Seoul

RUN apt update && apt-get install -y software-properties-common git libsndfile1 ffmpeg

RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt update && \
    apt install -y python3.9
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1


RUN apt-get install -y python3-pip && \
    pip3 install --upgrade pip && \
    pip install networkx==2.8.8

RUN python3.9 -m pip install git+https://github.com/myshell-ai/MeloTTS.git
RUN python3.9 -m unidic download



COPY ./requirements.txt /tmp/requirements.txt
RUN python3.9 -m pip install -r /tmp/requirements.txt
# RUN python3.9 -m pip install requests
# FROM nvidia/cuda:12.1.0-cudnn8-devel-ubuntu20.04

# ENV DEBIAN_FRONTEND=noninteractive
# ENV TZ=Asia/Seoul

# RUN apt update && apt-get install -y software-properties-common git libsndfile1

# RUN add-apt-repository ppa:deadsnakes/ppa && \
#     apt update && \
#     apt install -y python3.9
# RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1


# RUN apt-get install -y python3-pip && \
#     pip3 install --upgrade pip && \
#     python3.9 -m pip install networkx==2.6.3

# COPY ./requirements.txt /tmp/requirements.txt
# RUN python3.9 -m pip install -r /tmp/requirements.txt